const colors = {
  background: '#f9f9ff',
  surface: '#f9f9ff',
  surfaceDim: '#d2daeb',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#f0f3ff',
  surfaceContainer: '#e7eeff',
  surfaceContainerHigh: '#e1e8fa',
  surfaceContainerHighest: '#dbe3f4',
  surfaceVariant: '#dbe3f4',
  outline: '#737685',
  outlineVariant: '#c3c6d6',
  primary: '#003d9b',
  primaryContainer: '#0052cc',
  onPrimary: '#ffffff',
  onPrimaryContainer: '#c4d2ff',
  secondary: '#006d35',
  secondaryContainer: '#8df9a8',
  onSecondary: '#ffffff',
  onSecondaryContainer: '#007439',
  tertiary: '#802000',
  tertiaryContainer: '#a92e00',
  onTertiary: '#ffffff',
  onTertiaryContainer: '#ffc6b6',
  error: '#ba1a1a',
  onError: '#ffffff',
  onBackground: '#141c28',
  onSurface: '#141c28',
  onSurfaceVariant: '#434654',
  inverseSurface: '#29313e',
  inverseOnSurface: '#ebf1ff',
  inversePrimary: '#b2c5ff'
};

export default colors;
