services:
  # Spring Boot Backend Service
  backend:
    build: .
    container_name: backend-sedu
    ports:
      - "8080:8080" # Map local port 8080 to container port 8080
    environment:
      - SPRING_DATA_MONGODB_URI=${SPRING_DATA_MONGODB_URI}
    restart: unless-stopped
